// presets/react-validation-typeorm/resources/components/Layout.tsx
import { usePage } from "@lunoxjs/view-plugin-react";
import { useEffect, type FC, type PropsWithChildren } from "react";
interface LayoutProps {
  version: Record<string, string>;
}
const Layout: FC<PropsWithChildren<LayoutProps>> = ({
  version = { app: "", framework: "" },
  children = null,
}) => {
  const { sessions } = usePage();
  useEffect(() => {
    if (sessions?.message) {
      alert(sessions.message);
    }
  }, [sessions]);
  return (
    <div className="bg-gray-100 min-h-screen relative">
      <main className="mx-auto container py-10 xl:px-30 lg:px-10 px-4 font-sans pb-15 justify-center flex flex-col min-h-screen">
        {children}
        <footer className="absolute bottom-0 mb-5 left-0 right-0 px-10 text-gray-500 flex flex-row justify-between text-sm font-sans">
          <a
            className="flex flex-row items-center text-gray-500"
            href="https://github.com/kodepandai/lunox"
          >
            <div className="i-ant-design-github-filled text-xl mr-1" />
            <span>kodepandai/lunox</span>
          </a>
          <div>
            {`Lunox v.${version.app}(framework v.${version.framework})`}
          </div>
        </footer>
      </main>
    </div>
  );
};

export default Layout;

// presets/svelte-validation-typeorm/resources/lib/components/Layout.svelte
<script lang="ts">
    import { page } from "@lunoxjs/view-plugin-svelte";
    import { Toaster } from "$lib/components/ui/sonner";
    import { toast } from "svelte-sonner";
    import { ModeWatcher } from "mode-watcher";
    import LightSwitch from "$lib/components/LightSwitch.svelte";
    export let version: Record<string, string> = {
        app: "",
        framework: "",
    };

    $: if ($page?.sessions?.message && !import.meta.env.SSR) {
        toast.error($page?.sessions?.message, {
            cancel: {
                label: "close"
            }
        });
    }
</script>

<div class="bg-secondary min-h-screen relative">
    <main
        class="mx-auto container py-10 xl:px-30 lg:px-10 px-4 font-sans pb-15 justify-center flex flex-col min-h-screen"
    >
        <LightSwitch class="absolute top-5 right-5"/>
        <slot />
        <footer
            class="absolute bottom-0 mb-5 left-0 right-0 px-10 text-gray-500 flex flex-row justify-between text-sm font-sans"
        >
            <a
                class="flex flex-row items-center text-gray-500"
                href="https://github.com/kodepandai/lunox"
            >
                <div class="icon-[ant-design--github-filled] text-xl mr-1" />
                <span>kodepandai/lunox</span>
            </a>
            <div>
                Lunox v.{version.app}(framework v.{version.framework})
            </div>
        </footer>
    </main>
</div>
<Toaster />
<ModeWatcher />
