// presets/react/resources/components/Input.tsx
import { errors } from "@lunoxjs/view/client";

const Input = ({
  name = "",
  defaultValue = undefined,
  type = "text",
  placeholder = "",
}) => {
  return (
    <div className="mb-3 flex flex-col">
      <label htmlFor={name} className="text-sm text-gray-800">
        {name}
      </label>
      <input
        type={type}
        name={name}
        defaultValue={defaultValue}
        className="border border-yellow-200 p-2 rounded focus:outline-yellow"
        placeholder={placeholder}
      />
      {errors(name) && (
        <small className="text-red">{errors(name).message} </small>
      )}
    </div>
  );
};

export default Input;

// presets/svelte-validation-typeorm/resources/components/Input.svelte
<script lang="ts">
    export let type: "text" | "password";
    export let name: string;
    export let label: string = "";
    export let placeholder: string;
    export let value: string;
    import { errors } from "@lunoxjs/view/client";
</script>

<div class="mb-3 flex flex-col">
    <label for={name} class="text-sm text-gray-800">{label || name}</label>
    <input
        {value}
        {type}
        {name}
        class="border border-yellow-200 p-2 rounded focus:outline-yellow"
        {placeholder}
    />
    {#if errors(name)}
        <small class="text-red">{errors(name).message} </small>
    {/if}
</div>
