// presets/react-validation-typeorm/resources/lib/components/ui/input-wrapper.tsx
import React, { HTMLAttributes } from "react";
import { Label } from "./label";

export interface InputWrapperProps extends HTMLAttributes<HTMLDivElement> {
  labelPosition?: "first" | "end";
  label?: string;
  htmlFor?: string;
  required?: boolean;
  error?: string;
  className?: string;
}

const InputWrapper = React.forwardRef<
  HTMLDivElement,
  React.PropsWithChildren<InputWrapperProps>
>(
  (
    {
      htmlFor,
      labelPosition = "first",
      label,
      required = false,
      error,
      children,
      className,
    },
    ref,
  ) => {
    return (
      <div ref={ref} className={className}>
        {labelPosition == "first" && label && (
          <Label htmlFor={htmlFor}>{label}</Label>
        )}
        {required && <i className="text-destructive">*</i>}
        {children}
        {labelPosition == "end" && label && (
          <Label htmlFor={htmlFor}>{label}</Label>
        )}
        {error && <span className="text-xs text-destructive">{error}</span>}
      </div>
    );
  },
);
InputWrapper.displayName = "InputWrapper";

export { InputWrapper };

// presets/svelte-validation-eloquent/resources/lib/components/ui/input/input-wrapper.svelte
<script lang="ts">
    import Label from "$lib/components/ui/label/label.svelte";
    export let labelPosition: "first" | "end" = "first";
    export let label: string | undefined = undefined;
    export let required: boolean | null | undefined = undefined;
    export let error: string | undefined = undefined;
    let htmlFor: string | undefined | null = undefined;
    export { htmlFor as for };
</script>

<div>
    {#if labelPosition == "first" && label}<Label for={htmlFor}>{label}</Label
        >{/if}
    {#if required}
        <i class="text-destructive">*</i>
    {/if}
    <slot />
    {#if labelPosition == "end" && label}<Label for={htmlFor}>{label}</Label
        >{/if}
    {#if error}
        <span class="text-xs text-destructive">{error}</span>
    {/if}
</div>
